MACOSX_SDK_VERSION:            # [osx and x86_64]
  - 11.0                       # [osx and x86_64]
c_compiler_version:            # [osx and x86_64]
  - 15                         # [osx and x86_64]
cxx_compiler_version:          # [osx and x86_64]
  - 15                         # [osx and x86_64]
